// Copyright (c) "Neo4j"
// Neo4j Sweden AB [http://neo4j.com]

package search

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/neo4j-labs/neo4j-mcp-canary/internal/config"
	"github.com/neo4j-labs/neo4j-mcp-canary/internal/tools"

	"github.com/neo4j/neo4j-go-driver/v6/neo4j"
	"github.com/neo4j/neo4j-go-driver/v6/neo4j/dbtype"
)

// embedTextQuery asks Neo4j's GenAI plugin to generate an embedding
// server-side. Used for every provider except EmbeddingProviderOpenAI (see
// generateEmbedding) — those three (azure-openai/vertexai/bedrock-titan)
// have auth schemes (Azure OAuth, GCP service-account tokens, AWS SigV4)
// already implemented there, not worth reimplementing here. ai.text.embed
// is a function, not a procedure — it has no write effect on the graph, so
// this is safe to run as a read query even though it reaches out to an
// external provider API.
const embedTextQuery = "RETURN ai.text.embed($text, $embeddingProvider, $embeddingConfiguration) AS vector"

// defaultOpenAIBaseURL is generateEmbeddingViaOpenAI's target when
// Configuration["baseUrl"] is unset — the real OpenAI API.
const defaultOpenAIBaseURL = "https://api.openai.com/v1"

// generateEmbedding produces an embedding for text via the instance's
// configured GenAI provider. EmbeddingProviderOpenAI is generated by this
// MCP server itself, calling an OpenAI-compatible /embeddings endpoint
// directly (see generateEmbeddingViaOpenAI) — every other provider is
// generated by asking Neo4j's ai.text.embed instead (see embedTextQuery).
// Shared by set-vector-property's `text` field and
// check-embedding-dimensions.
func generateEmbedding(ctx context.Context, deps *tools.ToolDependencies, text string, embConf *config.EmbeddingConfig) ([]float64, error) {
	if embConf.Provider == config.EmbeddingProviderOpenAI {
		return generateEmbeddingViaOpenAI(ctx, text, embConf)
	}

	records, err := deps.DBService.ExecuteReadQuery(ctx, embedTextQuery, map[string]any{
		"text":                   text,
		"embeddingProvider":      string(embConf.Provider),
		"embeddingConfiguration": embConf.Configuration,
	})
	if err != nil {
		return nil, err
	}
	if len(records) == 0 {
		return nil, fmt.Errorf("ai.text.embed returned no rows")
	}
	raw, ok := records[0].Get("vector")
	if !ok {
		return nil, fmt.Errorf("missing 'vector' column in ai.text.embed result")
	}
	return vectorToFloat64Slice(raw)
}

// generateEmbeddingViaOpenAI calls an OpenAI-compatible /embeddings
// endpoint directly from this MCP server, bypassing Neo4j entirely.
// Configuration["baseUrl"] (optional, defaulting to defaultOpenAIBaseURL)
// lets this reach any OpenAI-compatible local server (LM Studio, Ollama)
// instead of the real OpenAI API — no Neo4j-side GenAI plugin install or
// genai.conf needed for this provider, unlike the other three (verified
// against a local LM Studio instance serving nomic-embed-text-v1.5).
func generateEmbeddingViaOpenAI(ctx context.Context, text string, embConf *config.EmbeddingConfig) ([]float64, error) {
	baseURL := embConf.Configuration["baseUrl"]
	if baseURL == "" {
		baseURL = defaultOpenAIBaseURL
	}
	baseURL = strings.TrimSuffix(baseURL, "/")

	reqBody, err := json.Marshal(map[string]string{
		"model": embConf.Configuration["model"],
		"input": text,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to encode embeddings request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, baseURL+"/embeddings", bytes.NewReader(reqBody))
	if err != nil {
		return nil, fmt.Errorf("failed to build embeddings request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+embConf.Configuration["token"])

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("embeddings request to %s failed: %w", baseURL, err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read embeddings response from %s: %w", baseURL, err)
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("embeddings request to %s returned %s: %s", baseURL, resp.Status, string(body))
	}

	var parsed struct {
		Data []struct {
			Embedding []float64 `json:"embedding"`
		} `json:"data"`
	}
	if err := json.Unmarshal(body, &parsed); err != nil {
		return nil, fmt.Errorf("failed to decode embeddings response from %s: %w", baseURL, err)
	}
	if len(parsed.Data) == 0 || len(parsed.Data[0].Embedding) == 0 {
		return nil, fmt.Errorf("embeddings response from %s contained no embedding data", baseURL)
	}
	return parsed.Data[0].Embedding, nil
}

// vectorToFloat64Slice decodes a driver-returned VECTOR column.
// ai.text.embed's return type is VECTOR (not a plain LIST<FLOAT>), which
// neo4j-go-driver decodes as one of the six concrete instantiations of the
// generic dbtype.Vector[T] (T constrained to float64|float32|int8|int16|
// int32|int64) — confirmed empirically against a live 2026.09 server
// (nomic-embed-text-v1.5 via an OpenAI-compatible local endpoint returned
// dbtype.Vector[float32]), not the []interface{} of float64 a plain
// LIST<FLOAT> column would decode as.
func vectorToFloat64Slice(raw any) ([]float64, error) {
	switch v := raw.(type) {
	case dbtype.Vector[float64]:
		return vectorElemsToFloat64(v.Elems), nil
	case dbtype.Vector[float32]:
		return vectorElemsToFloat64(v.Elems), nil
	case dbtype.Vector[int8]:
		return vectorElemsToFloat64(v.Elems), nil
	case dbtype.Vector[int16]:
		return vectorElemsToFloat64(v.Elems), nil
	case dbtype.Vector[int32]:
		return vectorElemsToFloat64(v.Elems), nil
	case dbtype.Vector[int64]:
		return vectorElemsToFloat64(v.Elems), nil
	default:
		return nil, fmt.Errorf("invalid vector type returned by ai.text.embed: %T", raw)
	}
}

func vectorElemsToFloat64[T dbtype.VectorElement](elems []T) []float64 {
	out := make([]float64, len(elems))
	for i, e := range elems {
		out[i] = float64(e)
	}
	return out
}

// vectorIndexDimensionsByLabelOrType looks up the configured vector.dimensions
// of the vector index (if any) covering entityType/labelOrType/property, via
// SHOW INDEXES' options column — the only place the resolved vector.*
// config is exposed; there is no dedicated dimensions column (confirmed
// against a live 2026.09 server: SHOW INDEXES YIELD options returns
// {indexConfig: {`vector.dimensions`: N, ...}} for a VECTOR-type row).
// found is false (not an error) when no matching index exists yet — the
// caller can still write a vector before an index is created on it.
func vectorIndexDimensionsByLabelOrType(ctx context.Context, deps *tools.ToolDependencies, entityType, labelOrType, property string) (dimensions int64, found bool, err error) {
	records, err := deps.DBService.ExecuteReadQuery(ctx, lookupVectorIndexDimensionsQuery, map[string]any{
		"entityType":  entityType,
		"labelOrType": labelOrType,
		"property":    property,
	})
	if err != nil {
		return 0, false, err
	}
	if len(records) == 0 {
		return 0, false, nil
	}
	dims, err := vectorDimensionsFromOptions(records[0])
	if err != nil {
		return 0, false, err
	}
	return dims, true, nil
}

const lookupVectorIndexDimensionsQuery = "SHOW INDEXES YIELD type, entityType, labelsOrTypes, properties, options " +
	"WHERE type = 'VECTOR' AND entityType = $entityType AND $labelOrType IN labelsOrTypes AND $property IN properties"

// vectorIndexByName fetches one named index's type and configured
// vector.dimensions, for check-embedding-dimensions — which, unlike
// set-vector-property, is handed an index name directly rather than a
// label/property pair to match against.
func vectorIndexByName(ctx context.Context, deps *tools.ToolDependencies, name string) (dimensions int64, err error) {
	records, err := deps.DBService.ExecuteReadQuery(ctx, showVectorIndexByNameQuery, map[string]any{"name": name})
	if err != nil {
		return 0, err
	}
	if len(records) == 0 {
		return 0, fmt.Errorf("no index named %q was found", name)
	}
	record := records[0]
	indexType, err := stringValue(record, "type")
	if err != nil {
		return 0, err
	}
	if indexType != "VECTOR" {
		return 0, fmt.Errorf("index %q is a %s index, not VECTOR", name, indexType)
	}
	return vectorDimensionsFromOptions(record)
}

const showVectorIndexByNameQuery = "SHOW INDEXES YIELD name, type, options WHERE name = $name"

// vectorDimensionsFromOptions extracts vector.dimensions from a SHOW
// INDEXES record's options column: {indexConfig: {`vector.dimensions`: N,
// ...}}.
func vectorDimensionsFromOptions(record *neo4j.Record) (int64, error) {
	optionsRaw, ok := record.Get("options")
	if !ok {
		return 0, fmt.Errorf("missing 'options' column in SHOW INDEXES record")
	}
	options, ok := optionsRaw.(map[string]any)
	if !ok {
		return 0, fmt.Errorf("invalid 'options' type in SHOW INDEXES record")
	}
	indexConfig, ok := options["indexConfig"].(map[string]any)
	if !ok {
		return 0, fmt.Errorf("missing or invalid 'indexConfig' in SHOW INDEXES options")
	}
	dimsRaw, ok := indexConfig["vector.dimensions"]
	if !ok {
		return 0, fmt.Errorf("missing 'vector.dimensions' in SHOW INDEXES options.indexConfig")
	}
	dims, ok := dimsRaw.(int64)
	if !ok {
		return 0, fmt.Errorf("invalid 'vector.dimensions' type in SHOW INDEXES options.indexConfig")
	}
	return dims, nil
}
