// Copyright (c) "Neo4j"
// Neo4j Sweden AB [http://neo4j.com]

package config

import (
	"fmt"
	"regexp"
	"slices"
	"strings"
)

// InstanceAuthType selects how the server connects to a single configured
// Neo4j instance in multi-instance HTTP mode (see NeoInstance).
type InstanceAuthType string

const (
	// InstanceAuthBasic uses a static service-account username/password
	// stored in the config file to connect to Neo4j, regardless of what the
	// calling MCP client presents. Because this bypasses any per-client
	// Neo4j credential, a client must still present one of Auth.APIKeys in
	// the configured API-key header to use the instance at all — otherwise
	// any caller reaching this instance's route would ride on the shared
	// service account with no authentication whatsoever.
	InstanceAuthBasic InstanceAuthType = "basic"
	// InstanceAuthBasicPassthrough forwards the calling client's own HTTP
	// Basic Auth credentials to Neo4j as-is (the same behavior single-
	// instance HTTP mode has always had), scoped to this one instance.
	InstanceAuthBasicPassthrough InstanceAuthType = "basic_passthrough" // #nosec G101 -- an auth-type identifier, not a credential
	// InstanceAuthBearer verifies the calling client's Bearer token (issuer,
	// audience, signature, expiry) against Auth.Issuer/JWKSURI/Audience,
	// then forwards the same token to Neo4j.
	InstanceAuthBearer InstanceAuthType = "bearer"
)

// ValidInstanceAuthTypes defines the allowed InstanceAuthType values.
var ValidInstanceAuthTypes = []InstanceAuthType{InstanceAuthBasic, InstanceAuthBasicPassthrough, InstanceAuthBearer}

// instanceNamePattern constrains NeoInstance.Name to a safe, single URL path
// segment, since the name is used directly to route requests to
// "/<name>/mcp" (see internal/server).
var instanceNamePattern = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_-]{0,62}$`)

// reservedInstanceNames are path segments this server already uses (or is
// expected to use) for other purposes, so they can't double as instance
// names.
var reservedInstanceNames = map[string]bool{
	"mcp":         true,
	".well-known": true,
}

// InstanceAuth describes one instance's connection auth, discriminated by
// Type. Only the fields relevant to that Type may be set; ValidateInstances
// rejects fields left over from another type so a config entry can't carry
// dead, confusing settings.
type InstanceAuth struct {
	Type InstanceAuthType `json:"type"`

	// Username/Password are required for InstanceAuthBasic: the static
	// service-account credentials this server connects to Neo4j with.
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
	// APIKeys are the client-facing shared secrets a caller must present
	// (in the configured API-key header) to use an InstanceAuthBasic
	// instance. Required — at least one non-empty entry.
	APIKeys []string `json:"api_keys,omitempty"`

	// Issuer/JWKSURI/Audience are required for InstanceAuthBearer: the
	// identity provider this server verifies incoming bearer tokens
	// against before forwarding them to Neo4j.
	Issuer   string `json:"issuer,omitempty"`
	JWKSURI  string `json:"jwks_uri,omitempty"`
	Audience string `json:"audience,omitempty"`
}

// NeoInstance is one entry in the config file's top-level neo4j_instances
// list (see instancesKey in configfile.go). Unlike every other Config field,
// this list is intentionally unreachable from CLI flags or environment
// variables — see the comment on Config.Instances.
type NeoInstance struct {
	Name     string       `json:"name"`
	URI      string       `json:"uri"`
	Database string       `json:"database"`
	Auth     InstanceAuth `json:"auth"`
	// Embedding optionally configures a Neo4j GenAI plugin provider so
	// set-vector-property can generate an embedding server-side (via its
	// `text` field, using Neo4j's own ai.text.embed function) instead of
	// requiring the caller to supply a pre-computed vector. Nil means this
	// instance only supports caller-supplied vectors.
	Embedding *EmbeddingConfig `json:"embedding,omitempty"`
}

// EmbeddingProvider selects which service generates an embedding.
// EmbeddingProviderOpenAI is generated by this MCP server itself, calling
// an OpenAI-compatible /embeddings endpoint directly (see
// internal/tools/search/embedding.go's generateEmbeddingViaOpenAI) — its
// optional Configuration["baseUrl"] key can redirect it to any
// OpenAI-compatible local server (e.g. LM Studio, Ollama), verified
// end-to-end against LM Studio/nomic-embed-text-v1.5, with no Neo4j-side
// GenAI plugin/config needed at all for this provider. The other three
// values match Neo4j's own ai.text.embed function's provider argument
// (accepted case-insensitively by Neo4j, but normalized to this
// lowercase-hyphenated form here — see
// https://neo4j.com/docs/genai/plugin/current/embeddings/) and are
// generated by Neo4j itself, not this server.
type EmbeddingProvider string

const (
	EmbeddingProviderOpenAI       EmbeddingProvider = "openai"
	EmbeddingProviderAzureOpenAI  EmbeddingProvider = "azure-openai"
	EmbeddingProviderVertexAI     EmbeddingProvider = "vertexai"
	EmbeddingProviderBedrockTitan EmbeddingProvider = "bedrock-titan"
)

// ValidEmbeddingProviders defines the allowed EmbeddingProvider values.
var ValidEmbeddingProviders = []EmbeddingProvider{
	EmbeddingProviderOpenAI, EmbeddingProviderAzureOpenAI, EmbeddingProviderVertexAI, EmbeddingProviderBedrockTitan,
}

// EmbeddingConfig is one instance's GenAI embedding-provider configuration.
// Configuration holds the provider-specific settings needed to generate an
// embedding (API credentials, model, region, etc. — see
// embeddingProviderRequiredKeys, plus the openai-only optional "baseUrl").
// For the three non-openai providers this is passed straight through to
// ai.text.embed, every key of which is a plain string, so this deliberately
// doesn't support that function's optional non-string keys (e.g. an
// integer maxBatchSize or a provider's vendorOptions map) — a caller
// needing those can still supply a pre-computed vector directly instead of
// text.
type EmbeddingConfig struct {
	Provider      EmbeddingProvider `json:"provider"`
	Configuration map[string]string `json:"configuration"`
}

// embeddingProviderRequiredKeys lists the mandatory Configuration keys for
// each provider, per Neo4j's ai.text.embed docs. VertexAI additionally
// requires exactly one of "apiKey"/"token", checked separately in
// validateEmbeddingConfig since that's an OR rather than an AND.
var embeddingProviderRequiredKeys = map[EmbeddingProvider][]string{
	EmbeddingProviderOpenAI:       {"token", "model"},
	EmbeddingProviderAzureOpenAI:  {"token", "resource", "model"},
	EmbeddingProviderVertexAI:     {"model", "project", "region"},
	EmbeddingProviderBedrockTitan: {"model", "region", "accessKeyId", "secretAccessKey"},
}

func validateEmbeddingConfig(e EmbeddingConfig) error {
	if !slices.Contains(ValidEmbeddingProviders, e.Provider) {
		return fmt.Errorf("embedding.provider %q must be one of %v", e.Provider, ValidEmbeddingProviders)
	}
	for _, key := range embeddingProviderRequiredKeys[e.Provider] {
		if strings.TrimSpace(e.Configuration[key]) == "" {
			return fmt.Errorf("embedding.provider %q requires a non-empty embedding.configuration[%q]", e.Provider, key)
		}
	}
	if e.Provider == EmbeddingProviderVertexAI && e.Configuration["apiKey"] == "" && e.Configuration["token"] == "" {
		return fmt.Errorf(`embedding.provider "vertexai" requires embedding.configuration["apiKey"] or ["token"]`)
	}
	// baseUrl only means anything for openai (this server's own direct
	// HTTP call, not Neo4j's ai.text.embed) — reject it elsewhere so a
	// caller who assumes it works like Neo4j's genai.*.baseurl settings
	// (which apply per-provider, server-side) gets a clear error instead
	// of a silently-ignored config key.
	if e.Provider != EmbeddingProviderOpenAI && e.Configuration["baseUrl"] != "" {
		return fmt.Errorf(`embedding.configuration["baseUrl"] is only used by embedding.provider "openai"; other providers are generated by Neo4j's ai.text.embed and don't support a per-call base URL override`)
	}
	return nil
}

// ValidateInstances validates a decoded neo4j_instances list: instance names
// are non-empty, unique, and safe single URL path segments; every entry has
// a URI and a recognized, fully-populated auth type.
func ValidateInstances(instances []NeoInstance) error {
	if len(instances) == 0 {
		return fmt.Errorf("neo4j_instances must contain at least one instance if present")
	}

	seen := make(map[string]bool, len(instances))
	for i, inst := range instances {
		if inst.Name == "" {
			return fmt.Errorf("neo4j_instances[%d]: name is required", i)
		}
		if !instanceNamePattern.MatchString(inst.Name) {
			return fmt.Errorf("neo4j_instances[%d]: name %q must match %s (it is used directly as a URL path segment, e.g. /%s/mcp)", i, inst.Name, instanceNamePattern.String(), inst.Name)
		}
		if reservedInstanceNames[inst.Name] {
			return fmt.Errorf("neo4j_instances[%d]: name %q is reserved", i, inst.Name)
		}
		if seen[inst.Name] {
			return fmt.Errorf("neo4j_instances[%d]: duplicate instance name %q", i, inst.Name)
		}
		seen[inst.Name] = true

		if inst.URI == "" {
			return fmt.Errorf("neo4j_instances[%d] (%s): uri is required", i, inst.Name)
		}

		if err := validateInstanceAuth(inst.Auth); err != nil {
			return fmt.Errorf("neo4j_instances[%d] (%s): %w", i, inst.Name, err)
		}

		if inst.Embedding != nil {
			if err := validateEmbeddingConfig(*inst.Embedding); err != nil {
				return fmt.Errorf("neo4j_instances[%d] (%s): %w", i, inst.Name, err)
			}
		}
	}
	return nil
}

func validateInstanceAuth(a InstanceAuth) error {
	if !slices.Contains(ValidInstanceAuthTypes, a.Type) {
		return fmt.Errorf("auth.type %q must be one of %v", a.Type, ValidInstanceAuthTypes)
	}

	switch a.Type {
	case InstanceAuthBasic:
		if a.Username == "" || a.Password == "" {
			return fmt.Errorf("auth.type %q requires auth.username and auth.password", a.Type)
		}
		if len(a.APIKeys) == 0 {
			return fmt.Errorf("auth.type %q requires at least one auth.api_keys entry, so a client must authenticate to use the shared service account", a.Type)
		}
		for _, k := range a.APIKeys {
			if strings.TrimSpace(k) == "" {
				return fmt.Errorf("auth.api_keys entries must not be empty")
			}
		}
		if a.Issuer != "" || a.JWKSURI != "" || a.Audience != "" {
			return fmt.Errorf("auth.type %q does not use auth.issuer/auth.jwks_uri/auth.audience", a.Type)
		}
	case InstanceAuthBasicPassthrough:
		if a.Username != "" || a.Password != "" || len(a.APIKeys) != 0 || a.Issuer != "" || a.JWKSURI != "" || a.Audience != "" {
			return fmt.Errorf("auth.type %q does not use username/password/api_keys/issuer/jwks_uri/audience", a.Type)
		}
	case InstanceAuthBearer:
		if a.Issuer == "" || a.JWKSURI == "" || a.Audience == "" {
			return fmt.Errorf("auth.type %q requires auth.issuer, auth.jwks_uri, and auth.audience", a.Type)
		}
		if a.Username != "" || a.Password != "" || len(a.APIKeys) != 0 {
			return fmt.Errorf("auth.type %q does not use username/password/api_keys", a.Type)
		}
	}
	return nil
}
